//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Imedisoft.Data.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Imedisoft.Data
{
    public partial class AppointmentFieldDefinitions
	{
		public static AppointmentFieldDefinition FromReader(MySqlDataReader dataReader)
		{
			return new AppointmentFieldDefinition
			{
				Id = (long)dataReader["id"],
				Name = (string)dataReader["name"],
				Type = (int)dataReader["type"],
				PickList = (string)dataReader["pick_list"]
			};
		}

		/// <summary>
		/// Selects a single ApptFieldDef object from the database using the specified SQL command.
		/// </summary>
		/// <param name="command">The SELECT command to execute.</param>
		/// <param name="parameters">The (optional) command parameters.</param>
		public static AppointmentFieldDefinition SelectOne(string command, params MySqlParameter[] parameters)
			=> Database.SelectOne(command, FromReader, parameters);

		/// <summary>
		/// Selects the <see cref="AppointmentFieldDefinition"/> object with the specified key from the database.
		/// </summary>
		/// <param name="id">The primary key of the <see cref="AppointmentFieldDefinition"/> to select.</param>
		public static AppointmentFieldDefinition SelectOne(long id)
			=> SelectOne("SELECT * FROM `appt_field_definitions` WHERE `id` = " + id);

		/// <summary>
		/// Selects multiple <see cref="AppointmentFieldDefinition"/> objects from the database using the specified SQL command.
		/// </summary>
		/// <param name="command">The SELECT command to execute.</param>
		/// <param name="parameters">The (optional) command parameters.</param>
		public static IEnumerable<AppointmentFieldDefinition> SelectMany(string command, params MySqlParameter[] parameters)
			=> Database.SelectMany(command, FromReader, parameters);

		/// <summary>
		/// Inserts the specified <see cref="AppointmentFieldDefinition"/> into the database.
		/// </summary>
		/// <param name="apptFieldDef">The <see cref="AppointmentFieldDefinition"/> to insert into the database.</param>
		private static long ExecuteInsert(AppointmentFieldDefinition apptFieldDef)
			=> apptFieldDef.Id = Database.ExecuteInsert(
				"INSERT INTO `appt_field_definitions` " +
				"(`name`, `type`, `pick_list`) " +
				"VALUES (" +
					"@name, @type, @pick_list" +
				")",
					new MySqlParameter("name", apptFieldDef.Name ?? ""),
					new MySqlParameter("type", (int)apptFieldDef.Type),
					new MySqlParameter("pick_list", apptFieldDef.PickList ?? ""));

		/// <summary>
		/// Updates the specified <see cref="AppointmentFieldDefinition"/> in the database.
		/// </summary>
		/// <param name="apptFieldDef">The <see cref="AppointmentFieldDefinition"/> to update.</param>
		private static void ExecuteUpdate(AppointmentFieldDefinition apptFieldDef)
			=> Database.ExecuteNonQuery(
				"UPDATE `appt_field_definitions` SET " +
					"`name` = @name, " +
					"`type` = @type, " +
					"`pick_list` = @pick_list " +
				"WHERE `id` = @id",
					new MySqlParameter("id", apptFieldDef.Id),
					new MySqlParameter("name", apptFieldDef.Name ?? ""),
					new MySqlParameter("type", (int)apptFieldDef.Type),
					new MySqlParameter("pick_list", apptFieldDef.PickList ?? ""));

		/// <summary>
		/// Deletes a single <see cref="AppointmentFieldDefinition"/> object from the database.
		/// </summary>
		/// <param name="id">The primary key of the <see cref="AppointmentFieldDefinition"/> to delete.</param>
		private static void ExecuteDelete(long id)
			 => Database.ExecuteNonQuery("DELETE FROM `appt_field_definitions` WHERE `id` = " + id);

		/// <summary>
		/// Deletes the specified <see cref="AppointmentFieldDefinition"/> object from the database.
		/// </summary>
		/// <param name="apptFieldDef">The <see cref="AppointmentFieldDefinition"/> to delete.</param>
		private static void ExecuteDelete(AppointmentFieldDefinition apptFieldDef)
			=> ExecuteDelete(apptFieldDef.Id);
	}
}
