//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Imedisoft.Data.Models;
using MySql.Data.MySqlClient;
using System.Collections.Generic;

namespace Imedisoft.Data
{
    public partial class AutoNotePrompts
	{
		public static AutoNotePrompt FromReader(MySqlDataReader dataReader)
		{
			return new AutoNotePrompt
			{
				Id = (long)dataReader["id"],
				Description = (string)dataReader["description"],
				Type = (string)dataReader["type"],
				Label = (string)dataReader["label"],
				Options = (string)dataReader["options"]
			};
		}

		/// <summary>
		/// Selects a single AutoNoteControl object from the database using the specified SQL command.
		/// </summary>
		/// <param name="command">The SELECT command to execute.</param>
		/// <param name="parameters">The (optional) command parameters.</param>
		public static AutoNotePrompt SelectOne(string command, params MySqlParameter[] parameters)
			=> Database.SelectOne(command, FromReader, parameters);

		/// <summary>
		/// Selects the <see cref="AutoNotePrompt"/> object with the specified key from the database.
		/// </summary>
		/// <param name="id">The primary key of the <see cref="AutoNotePrompt"/> to select.</param>
		public static AutoNotePrompt SelectOne(long id)
			=> SelectOne("SELECT * FROM `auto_note_prompts` WHERE `id` = " + id);

		/// <summary>
		/// Selects multiple <see cref="AutoNotePrompt"/> objects from the database using the specified SQL command.
		/// </summary>
		/// <param name="command">The SELECT command to execute.</param>
		/// <param name="parameters">The (optional) command parameters.</param>
		public static IEnumerable<AutoNotePrompt> SelectMany(string command, params MySqlParameter[] parameters)
			=> Database.SelectMany(command, FromReader, parameters);

		/// <summary>
		/// Inserts the specified <see cref="AutoNotePrompt"/> into the database.
		/// </summary>
		/// <param name="autoNoteControl">The <see cref="AutoNotePrompt"/> to insert into the database.</param>
		private static long ExecuteInsert(AutoNotePrompt autoNoteControl)
			=> autoNoteControl.Id = Database.ExecuteInsert(
				"INSERT INTO `auto_note_prompts` " +
				"(`description`, `type`, `label`, `options`) " +
				"VALUES (" +
					"@description, @type, @label, @options" +
				")",
					new MySqlParameter("description", autoNoteControl.Description ?? ""),
					new MySqlParameter("type", autoNoteControl.Type ?? ""),
					new MySqlParameter("label", autoNoteControl.Label ?? ""),
					new MySqlParameter("options", autoNoteControl.Options ?? ""));

		/// <summary>
		/// Updates the specified <see cref="AutoNotePrompt"/> in the database.
		/// </summary>
		/// <param name="autoNoteControl">The <see cref="AutoNotePrompt"/> to update.</param>
		private static void ExecuteUpdate(AutoNotePrompt autoNoteControl)
			=> Database.ExecuteNonQuery(
				"UPDATE `auto_note_prompts` SET " +
					"`description` = @description, " +
					"`type` = @type, " +
					"`label` = @label, " +
					"`options` = @options " +
				"WHERE `id` = @id",
					new MySqlParameter("id", autoNoteControl.Id),
					new MySqlParameter("description", autoNoteControl.Description ?? ""),
					new MySqlParameter("type", autoNoteControl.Type ?? ""),
					new MySqlParameter("label", autoNoteControl.Label ?? ""),
					new MySqlParameter("options", autoNoteControl.Options ?? ""));

		/// <summary>
		/// Deletes a single <see cref="AutoNotePrompt"/> object from the database.
		/// </summary>
		/// <param name="id">The primary key of the <see cref="AutoNotePrompt"/> to delete.</param>
		private static void ExecuteDelete(long id)
			 => Database.ExecuteNonQuery("DELETE FROM `auto_note_prompts` WHERE `id` = " + id);

		/// <summary>
		/// Deletes the specified <see cref="AutoNotePrompt"/> object from the database.
		/// </summary>
		/// <param name="autoNoteControl">The <see cref="AutoNotePrompt"/> to delete.</param>
		private static void ExecuteDelete(AutoNotePrompt autoNoteControl)
			=> ExecuteDelete(autoNoteControl.Id);
	}
}
