//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Imedisoft.Data.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Imedisoft.Data
{
	public partial class SchoolClasses
	{
		public static SchoolClass FromReader(MySqlDataReader dataReader)
		{
			return new SchoolClass
			{
				Id = (long)dataReader["id"],
				Year = (int)dataReader["year"],
				Description = (string)dataReader["description"]
			};
		}

		/// <summary>
		/// Selects a single SchoolClass object from the database using the specified SQL command.
		/// </summary>
		/// <param name="command">The SELECT command to execute.</param>
		/// <param name="parameters">The (optional) command parameters.</param>
		public static SchoolClass SelectOne(string command, params MySqlParameter[] parameters)
			=> Database.SelectOne(command, FromReader, parameters);

		/// <summary>
		/// Selects the <see cref="SchoolClass"/> object with the specified key from the database.
		/// </summary>
		/// <param name="id">The primary key of the <see cref="SchoolClass"/> to select.</param>
		public static SchoolClass SelectOne(long id)
			=> SelectOne("SELECT * FROM `school_classes` WHERE `id` = " + id);

		/// <summary>
		/// Selects multiple <see cref="SchoolClass"/> objects from the database using the specified SQL command.
		/// </summary>
		/// <param name="command">The SELECT command to execute.</param>
		/// <param name="parameters">The (optional) command parameters.</param>
		public static IEnumerable<SchoolClass> SelectMany(string command, params MySqlParameter[] parameters)
			=> Database.SelectMany(command, FromReader, parameters);

		/// <summary>
		/// Inserts the specified <see cref="SchoolClass"/> into the database.
		/// </summary>
		/// <param name="schoolClass">The <see cref="SchoolClass"/> to insert into the database.</param>
		private static long ExecuteInsert(SchoolClass schoolClass)
			=> schoolClass.Id = Database.ExecuteInsert(
				"INSERT INTO `school_classes` " +
				"(`year`, `description`) " +
				"VALUES (" +
					"@year, @description" +
				")",
					new MySqlParameter("year", schoolClass.Year),
					new MySqlParameter("description", schoolClass.Description ?? ""));

		/// <summary>
		/// Updates the specified <see cref="SchoolClass"/> in the database.
		/// </summary>
		/// <param name="schoolClass">The <see cref="SchoolClass"/> to update.</param>
		private static void ExecuteUpdate(SchoolClass schoolClass)
			=> Database.ExecuteNonQuery(
				"UPDATE `school_classes` SET " +
					"`year` = @year, " +
					"`description` = @description " +
				"WHERE `id` = @id",
					new MySqlParameter("id", schoolClass.Id),
					new MySqlParameter("year", schoolClass.Year),
					new MySqlParameter("description", schoolClass.Description ?? ""));

		/// <summary>
		/// Deletes a single <see cref="SchoolClass"/> object from the database.
		/// </summary>
		/// <param name="id">The primary key of the <see cref="SchoolClass"/> to delete.</param>
		private static void ExecuteDelete(long id)
			 => Database.ExecuteNonQuery("DELETE FROM `school_classes` WHERE `id` = " + id);

		/// <summary>
		/// Deletes the specified <see cref="SchoolClass"/> object from the database.
		/// </summary>
		/// <param name="schoolClass">The <see cref="SchoolClass"/> to delete.</param>
		private static void ExecuteDelete(SchoolClass schoolClass)
			=> ExecuteDelete(schoolClass.Id);
	}
}
