using Imedisoft.Data.Annotations;
using Imedisoft.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace OpenDentBusiness
{
	[Table("erx_logs")]
	public class ErxLog
	{
		[PrimaryKey]
		public long Id;

		/// <summary>
		/// The ID of the user that created the eRX.
		/// </summary>
		public long UserId;

		[ForeignKey(typeof(Patient), nameof(Patient.PatNum))]
		public long PatientId;

		/// <summary>
		/// The ID of the provider that the prescription request was sent by or on behalf of.
		/// </summary>
		[ForeignKey(typeof(Provider), nameof(Provider.Id))]
		public long ProviderId;

		public string MsgText;

		[Column(AutoGenerated = true)]
		public DateTime LastModifiedDate;
	}
}
