//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imedisoft.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Imedisoft.Translation.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbr.
        /// </summary>
        public static string Abbr {
            get {
                return ResourceManager.GetString("Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Type.
        /// </summary>
        public static string AdjustmentType {
            get {
                return ResourceManager.GetString("AdjustmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy.
        /// </summary>
        public static string Allergy {
            get {
                return ResourceManager.GetString("Allergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And {0} others....
        /// </summary>
        public static string AndXOthers {
            get {
                return ResourceManager.GetString("AndXOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Note(s) failed to export..
        /// </summary>
        public static string AutoNoteExportFailed {
            get {
                return ResourceManager.GetString("AutoNoteExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Note(s) successfully exported..
        /// </summary>
        public static string AutoNoteExportSuccess {
            get {
                return ResourceManager.GetString("AutoNoteExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Note(s) failed to import..
        /// </summary>
        public static string AutoNoteImportFailed {
            get {
                return ResourceManager.GetString("AutoNoteImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Notes successfully imported!
        ///
        ///Imported {0} new note(s) and {1} new prompt(s)..
        /// </summary>
        public static string AutoNoteImportSuccess {
            get {
                return ResourceManager.GetString("AutoNoteImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Number.
        /// </summary>
        public static string BankNumber {
            get {
                return ResourceManager.GetString("BankNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        public static string CancelWithMnemonic {
            get {
                return ResourceManager.GetString("CancelWithMnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete clinic because the following patients have appointments using it:.
        /// </summary>
        public static string CannotDeleteClinicInUseByAppointments {
            get {
                return ResourceManager.GetString("CannotDeleteClinicInUseByAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete clinic because the following patients have claim payments using it:.
        /// </summary>
        public static string CannotDeleteClinicInUseByClaimPayments {
            get {
                return ResourceManager.GetString("CannotDeleteClinicInUseByClaimPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete clinic because the following users are restricted to this clinic in security setup:.
        /// </summary>
        public static string CannotDeleteClinicInUseByClinicRestrictedUsers {
            get {
                return ResourceManager.GetString("CannotDeleteClinicInUseByClinicRestrictedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete clinic because the following operatories are using it:.
        /// </summary>
        public static string CannotDeleteClinicInUseByOperatories {
            get {
                return ResourceManager.GetString("CannotDeleteClinicInUseByOperatories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete clinic because it is in use by the following patients:.
        /// </summary>
        public static string CannotDeleteClinicInUseByPatients {
            get {
                return ResourceManager.GetString("CannotDeleteClinicInUseByPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete clinic because the following patients have payments using it:.
        /// </summary>
        public static string CannotDeleteClinicInUseByPayments {
            get {
                return ResourceManager.GetString("CannotDeleteClinicInUseByPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete clinic because the following patients have procedures using it:.
        /// </summary>
        public static string CannotDeleteClinicInUseByProcedures {
            get {
                return ResourceManager.GetString("CannotDeleteClinicInUseByProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete clinic because the following users are using it:.
        /// </summary>
        public static string CannotDeleteClinicInUseByUsers {
            get {
                return ResourceManager.GetString("CannotDeleteClinicInUseByUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have two Auto Code items with duplicate conditions..
        /// </summary>
        public static string CannotHaveAutoCodeItemsWithDuplicateConditions {
            get {
                return ResourceManager.GetString("CannotHaveAutoCodeItemsWithDuplicateConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected item?.
        /// </summary>
        public static string ConfirmDeleteSelectedItem {
            get {
                return ResourceManager.GetString("ConfirmDeleteSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected items?.
        /// </summary>
        public static string ConfirmDeleteSelectedItems {
            get {
                return ResourceManager.GetString("ConfirmDeleteSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a update available. Would you like to update now?.
        /// </summary>
        public static string ConfirmInstallUpdate {
            get {
                return ResourceManager.GetString("ConfirmInstallUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the selected category?.
        /// </summary>
        public static string ConfirmMoveSelectedCategory {
            get {
                return ResourceManager.GetString("ConfirmMoveSelectedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the selected category to the root level?.
        /// </summary>
        public static string ConfirmMoveSelectedCategoryToRootLevel {
            get {
                return ResourceManager.GetString("ConfirmMoveSelectedCategoryToRootLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the selected note?.
        /// </summary>
        public static string ConfirmMoveSelectedNote {
            get {
                return ResourceManager.GetString("ConfirmMoveSelectedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the selected note to the root level?.
        /// </summary>
        public static string ConfirmMoveSelectedNoteToRootLevel {
            get {
                return ResourceManager.GetString("ConfirmMoveSelectedNoteToRootLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing file?.
        /// </summary>
        public static string ConfirmOverwriteFile {
            get {
                return ResourceManager.GetString("ConfirmOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlled.
        /// </summary>
        public static string Controlled {
            get {
                return ResourceManager.GetString("Controlled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        public static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not copy contents to clipboard. Please try again..
        /// </summary>
        public static string CouldNotCopyContentsToClipboard {
            get {
                return ResourceManager.GetString("CouldNotCopyContentsToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County name already exists. Duplicate not allowed..
        /// </summary>
        public static string CountyNameAlreadyExists {
            get {
                return ResourceManager.GetString("CountyNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password incorrect..
        /// </summary>
        public static string CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date limitation.
        /// </summary>
        public static string DateLimitation {
            get {
                return ResourceManager.GetString("DateLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default text.
        /// </summary>
        public static string DefaultText {
            get {
                return ResourceManager.GetString("DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        public static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        public static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description can only contain letters, numbers, underscore, and space..
        /// </summary>
        public static string DescriptionCannotContainSpecialCharacters {
            get {
                return ResourceManager.GetString("DescriptionCannotContainSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Disable.
        /// </summary>
        public static string DisableWithMnemonic {
            get {
                return ResourceManager.GetString("DisableWithMnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug.
        /// </summary>
        public static string Drug {
            get {
                return ResourceManager.GetString("Drug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed.
        /// </summary>
        public static string Elapsed {
            get {
                return ResourceManager.GetString("Elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Enable.
        /// </summary>
        public static string EnableWithMnemonic {
            get {
                return ResourceManager.GetString("EnableWithMnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date.
        /// </summary>
        public static string EntryDate {
            get {
                return ResourceManager.GetString("EntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for updates..
        /// </summary>
        public static string ErrorCheckingForUpdates {
            get {
                return ResourceManager.GetString("ErrorCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating log file. {0}.
        /// </summary>
        public static string ErrorCreatingLogFile {
            get {
                return ResourceManager.GetString("ErrorCreatingLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open log file. {0}.
        /// </summary>
        public static string ErrorOpeningLogFile {
            get {
                return ResourceManager.GetString("ErrorOpeningLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file..
        /// </summary>
        public static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported.
        /// </summary>
        public static string Exported {
            get {
                return ResourceManager.GetString("Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Schedule.
        /// </summary>
        public static string FeeSchedule {
            get {
                return ResourceManager.GetString("FeeSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name already in use..
        /// </summary>
        public static string FieldNameAlreadyInUse {
            get {
                return ResourceManager.GetString("FieldNameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        public static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Proc..
        /// </summary>
        public static string HasProc {
            get {
                return ResourceManager.GetString("HasProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient privileges to perform this operation..
        /// </summary>
        public static string InsufficientPrivileges {
            get {
                return ResourceManager.GetString("InsufficientPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML..
        /// </summary>
        public static string InvalidXml {
            get {
                return ResourceManager.GetString("InvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Files.
        /// </summary>
        public static string JsonFiles {
            get {
                return ResourceManager.GetString("JsonFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List cannot be blank..
        /// </summary>
        public static string ListCannotBeBlank {
            get {
                return ResourceManager.GetString("ListCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked by Administrator..
        /// </summary>
        public static string LockedByAdministrator {
            get {
                return ResourceManager.GetString("LockedByAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked by Administrator before {0}..
        /// </summary>
        public static string LockedByAdministratorForDate {
            get {
                return ResourceManager.GetString("LockedByAdministratorForDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked by Administrator before {0} days..
        /// </summary>
        public static string LockedByAdministratorForDays {
            get {
                return ResourceManager.GetString("LockedByAdministratorForDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file created. Would you like to open the file?.
        /// </summary>
        public static string LogFileCreatedWouldYouLikeToOpenFile {
            get {
                return ResourceManager.GetString("LogFileCreatedWouldYouLikeToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication.
        /// </summary>
        public static string Medication {
            get {
                return ResourceManager.GetString("Medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MedLab Account Number entered is already in use by another clinic..
        /// </summary>
        public static string MedLabAccountInUseByAnotherClinic {
            get {
                return ResourceManager.GetString("MedLabAccountInUseByAnotherClinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meets.
        /// </summary>
        public static string Meets {
            get {
                return ResourceManager.GetString("Meets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Info.
        /// </summary>
        public static string MissingInfo {
            get {
                return ResourceManager.GetString("MissingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have at least one item in the list..
        /// </summary>
        public static string MustHaveAtLeastOneItemInList {
            get {
                return ResourceManager.GetString("MustHaveAtLeastOneItemInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to set up at least one allergy from EHR setup window..
        /// </summary>
        public static string NeedToSetupAtLeastOneAllergy {
            get {
                return ResourceManager.GetString("NeedToSetupAtLeastOneAllergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No Printers Installed.
        ///
        ///If you do have a printer installed, restarting the workstation may solve the problem..
        /// </summary>
        public static string NoPrintersInstalled {
            get {
                return ResourceManager.GetString("NoPrintersInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No queries in the Query Feed to log..
        /// </summary>
        public static string NoQueriesInTheQueryFeedToLog {
            get {
                return ResourceManager.GetString("NoQueriesInTheQueryFeedToLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stylesheet found..
        /// </summary>
        public static string NoStylesheetFound {
            get {
                return ResourceManager.GetString("NoStylesheetFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        public static string NotApplicableAbbr {
            get {
                return ResourceManager.GetString("NotApplicableAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string OperationComplete {
            get {
                return ResourceManager.GetString("OperationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to perform the requested operation. Reason: {0}..
        /// </summary>
        public static string OperationNowAllowedForReason {
            get {
                return ResourceManager.GetString("OperationNowAllowedForReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password cannot be empty..
        /// </summary>
        public static string PasswordCannotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password may not be blank when the strong password feature is turned on..
        /// </summary>
        public static string PasswordMayNotBeBlank {
            get {
                return ResourceManager.GetString("PasswordMayNotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least eight characters long when the strong password feature is turned on..
        /// </summary>
        public static string PasswordMustBeAtLeastEightCharacters {
            get {
                return ResourceManager.GetString("PasswordMustBeAtLeastEightCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lower case letter when the strong password feature is turned on..
        /// </summary>
        public static string PasswordMustContainAtLeastOneLowerCaseLetter {
            get {
                return ResourceManager.GetString("PasswordMustContainAtLeastOneLowerCaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number when the strong password feature is turned on..
        /// </summary>
        public static string PasswordMustContainAtLeastOneNumber {
            get {
                return ResourceManager.GetString("PasswordMustContainAtLeastOneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character when the &apos;strong passwords require a special character&apos; feature is turned on..
        /// </summary>
        public static string PasswordMustContainAtLeastOneSpecialCharacter {
            get {
                return ResourceManager.GetString("PasswordMustContainAtLeastOneSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one capital letter when the strong password feature is turned on..
        /// </summary>
        public static string PasswordMustContainAtLeastOneUpperCaseLetter {
            get {
                return ResourceManager.GetString("PasswordMustContainAtLeastOneUpperCaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient #.
        /// </summary>
        public static string PatientId {
            get {
                return ResourceManager.GetString("PatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick List.
        /// </summary>
        public static string PickList {
            get {
                return ResourceManager.GetString("PickList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an abbreviation..
        /// </summary>
        public static string PleaseEnterAbbreviation {
            get {
                return ResourceManager.GetString("PleaseEnterAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an API key..
        /// </summary>
        public static string PleaseEnterApiKey {
            get {
                return ResourceManager.GetString("PleaseEnterApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a autograph..
        /// </summary>
        public static string PleaseEnterAutograph {
            get {
                return ResourceManager.GetString("PleaseEnterAutograph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a code..
        /// </summary>
        public static string PleaseEnterCode {
            get {
                return ResourceManager.GetString("PleaseEnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a date..
        /// </summary>
        public static string PleaseEnterDate {
            get {
                return ResourceManager.GetString("PleaseEnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a description..
        /// </summary>
        public static string PleaseEnterDescription {
            get {
                return ResourceManager.GetString("PleaseEnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name..
        /// </summary>
        public static string PleaseEnterName {
            get {
                return ResourceManager.GetString("PleaseEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a note..
        /// </summary>
        public static string PleaseEnterNote {
            get {
                return ResourceManager.GetString("PleaseEnterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        public static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a response text..
        /// </summary>
        public static string PleaseEnterResponseText {
            get {
                return ResourceManager.GetString("PleaseEnterResponseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a title..
        /// </summary>
        public static string PleaseEnterTitle {
            get {
                return ResourceManager.GetString("PleaseEnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid amount..
        /// </summary>
        public static string PleaseEnterValidAmount {
            get {
                return ResourceManager.GetString("PleaseEnterValidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date..
        /// </summary>
        public static string PleaseEnterValidDate {
            get {
                return ResourceManager.GetString("PleaseEnterValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid interval..
        /// </summary>
        public static string PleaseEnterValidInterval {
            get {
                return ResourceManager.GetString("PleaseEnterValidInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid percentage..
        /// </summary>
        public static string PleaseEnterValidPercentage {
            get {
                return ResourceManager.GetString("PleaseEnterValidPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid start and stop dates..
        /// </summary>
        public static string PleaseEnterValidStartAndStopDates {
            get {
                return ResourceManager.GetString("PleaseEnterValidStartAndStopDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid year..
        /// </summary>
        public static string PleaseEnterValidYear {
            get {
                return ResourceManager.GetString("PleaseEnterValidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value..
        /// </summary>
        public static string PleaseEnterValue {
            get {
                return ResourceManager.GetString("PleaseEnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an account first..
        /// </summary>
        public static string PleaseSelectAccountFirst {
            get {
                return ResourceManager.GetString("PleaseSelectAccountFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an allergy..
        /// </summary>
        public static string PleaseSelectAllergy {
            get {
                return ResourceManager.GetString("PleaseSelectAllergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one condition..
        /// </summary>
        public static string PleaseSelectAtLeastOneCondition {
            get {
                return ResourceManager.GetString("PleaseSelectAtLeastOneCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one note..
        /// </summary>
        public static string PleaseSelectAtLeastOneNote {
            get {
                return ResourceManager.GetString("PleaseSelectAtLeastOneNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one response..
        /// </summary>
        public static string PleaseSelectAtLeastOneResponse {
            get {
                return ResourceManager.GetString("PleaseSelectAtLeastOneResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a code..
        /// </summary>
        public static string PleaseSelectCode {
            get {
                return ResourceManager.GetString("PleaseSelectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item..
        /// </summary>
        public static string PleaseSelectItem {
            get {
                return ResourceManager.GetString("PleaseSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item first..
        /// </summary>
        public static string PleaseSelectItemFirst {
            get {
                return ResourceManager.GetString("PleaseSelectItemFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a payment type..
        /// </summary>
        public static string PleaseSelectPaymentType {
            get {
                return ResourceManager.GetString("PleaseSelectPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a provider..
        /// </summary>
        public static string PleaseSelectProvider {
            get {
                return ResourceManager.GetString("PleaseSelectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a provider for insurance billing..
        /// </summary>
        public static string PleaseSelectProviderForInsuranceBilling {
            get {
                return ResourceManager.GetString("PleaseSelectProviderForInsuranceBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a response..
        /// </summary>
        public static string PleaseSelectResponse {
            get {
                return ResourceManager.GetString("PleaseSelectResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a type..
        /// </summary>
        public static string PleaseSelectType {
            get {
                return ResourceManager.GetString("PleaseSelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user..
        /// </summary>
        public static string PleaseSelectUser {
            get {
                return ResourceManager.GetString("PleaseSelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a group..
        /// </summary>
        public static string PleaseSelectUserGroup {
            get {
                return ResourceManager.GetString("PleaseSelectUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value type..
        /// </summary>
        public static string PleaseSelectValueType {
            get {
                return ResourceManager.GetString("PleaseSelectValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible responses
        ///(one line per item).
        /// </summary>
        public static string PossibleResponsesOneLinePerItem {
            get {
                return ResourceManager.GetString("PossibleResponsesOneLinePerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        public static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt Text.
        /// </summary>
        public static string PromptText {
            get {
                return ResourceManager.GetString("PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prov. #.
        /// </summary>
        public static string ProviderIdAbbr {
            get {
                return ResourceManager.GetString("ProviderIdAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        public static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Enter Password.
        /// </summary>
        public static string ReEnterPassword {
            get {
                return ResourceManager.GetString("ReEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested.
        /// </summary>
        public static string Requested {
            get {
                return ResourceManager.GetString("Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved..
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned.
        /// </summary>
        public static string Scanned {
            get {
                return ResourceManager.GetString("Scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a row from the Query Feed..
        /// </summary>
        public static string SelectRowFromQueryFeed {
            get {
                return ResourceManager.GetString("SelectRowFromQueryFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent..
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the graphics for computer &apos;{0}&apos; to simple..
        /// </summary>
        public static string SetGraphicsForComputerToSimple {
            get {
                return ResourceManager.GetString("SetGraphicsForComputerToSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shown.
        /// </summary>
        public static string Shown {
            get {
                return ResourceManager.GetString("Shown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        public static string Specialty {
            get {
                return ResourceManager.GetString("Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop monitoring queries before creating a log..
        /// </summary>
        public static string StopMonitoringQueriesBeforeCreatingLog {
            get {
                return ResourceManager.GetString("StopMonitoringQueriesBeforeCreatingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Picker.
        /// </summary>
        public static string StudentPicker {
            get {
                return ResourceManager.GetString("StudentPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (copy).
        /// </summary>
        public static string TagCopy {
            get {
                return ResourceManager.GetString("TagCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (hidden).
        /// </summary>
        public static string TagHidden {
            get {
                return ResourceManager.GetString("TagHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string TagNone {
            get {
                return ResourceManager.GetString("TagNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (null).
        /// </summary>
        public static string TagNull {
            get {
                return ResourceManager.GetString("TagNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following users could not be updated:.
        /// </summary>
        public static string TheFollowingUsersCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("TheFollowingUsersCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no update available..
        /// </summary>
        public static string ThereIsNoUpdateAvailable {
            get {
                return ResourceManager.GetString("ThereIsNoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been locked due to failed log in attempts.
        ///Call your security admin to unlock your account or wait at least 5 minutes..
        /// </summary>
        public static string TooManyFailedLogonAttempts {
            get {
                return ResourceManager.GetString("TooManyFailedLogonAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not hide this clinic as the following users are restricted to only this clinic:.
        /// </summary>
        public static string UnableToHideClinicWithClinicRestrictedUsers {
            get {
                return ResourceManager.GetString("UnableToHideClinicWithClinicRestrictedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Version: {0}.
        /// </summary>
        public static string UsingVersion {
            get {
                return ResourceManager.GetString("UsingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Version: {0} - Since: {1}.
        /// </summary>
        public static string UsingVersionSince {
            get {
                return ResourceManager.GetString("UsingVersionSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted.
        /// </summary>
        public static string Weighted {
            get {
                return ResourceManager.GetString("Weighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected a problem with an unofficial SNOMED CT code. Please correct the problem definition by going to Lists | Problems and choosing an official code from the SNOMED CT list..
        /// </summary>
        public static string YouHaveSelectedProblemWithUnofficialSnomedCode {
            get {
                return ResourceManager.GetString("YouHaveSelectedProblemWithUnofficialSnomedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter your username..
        /// </summary>
        public static string YouHaveToEnterYourUsername {
            get {
                return ResourceManager.GetString("YouHaveToEnterYourUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must change your password to a strong password due to the current security settings..
        /// </summary>
        public static string YouMustChangePasswordToStrongPasswordDueToSecuritySettings {
            get {
                return ResourceManager.GetString("YouMustChangePasswordToStrongPasswordDueToSecuritySettings", resourceCulture);
            }
        }
    }
}
