//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imedisoft.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecurityLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityLog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Imedisoft.Translation.SecurityLog", typeof(SecurityLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Setup window accesssed..
        /// </summary>
        public static string AccessedWindowUpdateSetup {
            get {
                return ResourceManager.GetString("AccessedWindowUpdateSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aging Complete - Aging Form.
        /// </summary>
        public static string AgingComplete {
            get {
                return ResourceManager.GetString("AgingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Aging - Aging Form.
        /// </summary>
        public static string AgingStart {
            get {
                return ResourceManager.GetString("AgingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Note Export.
        /// </summary>
        public static string AutoNoteExport {
            get {
                return ResourceManager.GetString("AutoNoteExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Note Import. Imported {0} new note(s) and {1} new prompt(s)..
        /// </summary>
        public static string AutoNoteImport {
            get {
                return ResourceManager.GetString("AutoNoteImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; has logged on..
        /// </summary>
        public static string UserHasLoggedOn {
            get {
                return ResourceManager.GetString("UserHasLoggedOn", resourceCulture);
            }
        }
    }
}
