using Imedisoft.Data.Annotations;
using System;

namespace Imedisoft.Data.Models
{
	[Table("medications")]
	public class Medication
	{
		[PrimaryKey]
		public long Id;

		/// <summary>
		///		<para>
		///			Name of the medication. User can change this.
		///		</para> 
		///		<para>
		///			If an RxCui is present, the RxNorm string can be pulled from the in-memory 
		///			table for UI display in addition to the name.
		///		</para>
		///	</summary>
		public string Name;

		/// <summary>
		///		<para>
		///			The ID of the generic variant of this medication.
		///		</para>
		///		<para>
		///			This is NULL for generic medications.
		///		</para>
		/// </summary>
		[ForeignKey(typeof(Medication), nameof(Id))]
		public long? GenericId;

		/// <summary>
		/// Gets a value indicating whether this medication is a generic medication.
		/// </summary>
		public bool IsGeneric => !GenericId.HasValue;

		/// <summary>
		/// Notes.
		/// </summary>
		public string Notes;

		[Column(AutoGenerated = true)]
		public DateTime LastModifiedDate;

		/// <summary>
		/// RxNorm Code identifier. We should have used a string type. Used by EHR in CQM. 
		/// But the queries should use medicationpat.RxCui, NOT this RxCui, because all 
		/// medicationpats (meds and orders) coming back from NewCrop will not have a FK to this 
		/// medication table. When this RxCui is modified by the user, then medicationpat.RxCui is 
		/// automatically updated where medicationpat.MedicationNum matches this medication.
		/// </summary>
		public string RxCui;
	}
}
