//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Imedisoft.Data;
using MySql.Data.MySqlClient;
using System;
using System.Collections;
using System.Collections.Generic;

namespace OpenDentBusiness.Crud
{
	public class AdjustmentCrud
	{
		public static Adjustment FromReader(MySqlDataReader dataReader)
		{
			return new Adjustment
			{
				AdjNum = (long)dataReader["AdjNum"],
				AdjDate = (DateTime)dataReader["AdjDate"],
				AdjAmt = (double)dataReader["AdjAmt"],
				PatNum = (long)dataReader["PatNum"],
				AdjType = (long)dataReader["AdjType"],
				ProvNum = (long)dataReader["ProvNum"],
				AdjNote = (string)dataReader["AdjNote"],
				ProcDate = (DateTime)dataReader["ProcDate"],
				ProcNum = (long)dataReader["ProcNum"],
				DateEntry = (DateTime)dataReader["DateEntry"],
				ClinicNum = (long)dataReader["ClinicNum"],
				StatementNum = (long)dataReader["StatementNum"],
				SecUserNumEntry = (long)dataReader["SecUserNumEntry"],
				SecDateTEdit = (DateTime)dataReader["SecDateTEdit"]
			};
		}

		/// <summary>
		/// Selects a single Adjustment object from the database using the specified SQL command.
		/// </summary>
		public static Adjustment SelectOne(string command)
			=> Database.SelectOne(command, FromReader);

		/// <summary>
		/// Selects a single <see cref="Adjustment"/> object from the database using the specified SQL command.
		/// </summary>
		public static Adjustment SelectOne(Int64 adjNum)
			=> SelectOne("SELECT * FROM `Adjustment` WHERE `AdjNum` = " + adjNum);

		/// <summary>
		/// Selects multiple <see cref="Adjustment"/> objects from the database using the specified SQL command.
		/// </summary>
		public static IEnumerable<Adjustment> SelectMany(string command)
			=> Database.SelectMany(command, FromReader);

		/// <summary>
		/// Inserts the specified <see cref="Adjustment"/> into the database.
		/// </summary>
		public static long Insert(Adjustment adjustment)
			=> adjustment.AdjNum = Database.ExecuteInsert(
				"INSERT INTO `Adjustment` " + 
				"(`AdjDate`, `AdjAmt`, `PatNum`, `AdjType`, `ProvNum`, `AdjNote`, `ProcDate`, `ProcNum`, `DateEntry`, `ClinicNum`, `StatementNum`, `SecUserNumEntry`, `SecDateTEdit`) " + 
				"VALUES (" + 
					"@AdjDate, @AdjAmt, @PatNum, @AdjType, @ProvNum, @AdjNote, @ProcDate, @ProcNum, @DateEntry, @ClinicNum, @StatementNum, @SecUserNumEntry, @SecDateTEdit" + 
				")");

		/// <summary>
		/// Updates the specified <see cref="Adjustment"/> in the database.
		/// </summary>
		public static void Update(Adjustment adjustment)
			=> Database.ExecuteNonQuery(
				"UPDATE `Adjustment` SET " + 
					"`AdjDate` = @AdjDate, " + 
					"`AdjAmt` = @AdjAmt, " + 
					"`PatNum` = @PatNum, " + 
					"`AdjType` = @AdjType, " + 
					"`ProvNum` = @ProvNum, " + 
					"`AdjNote` = @AdjNote, " + 
					"`ProcDate` = @ProcDate, " + 
					"`ProcNum` = @ProcNum, " + 
					"`DateEntry` = @DateEntry, " + 
					"`ClinicNum` = @ClinicNum, " + 
					"`StatementNum` = @StatementNum, " + 
					"`SecUserNumEntry` = @SecUserNumEntry, " + 
					"`SecDateTEdit` = @SecDateTEdit " + 
				"WHERE `AdjNum` = @AdjNum",
					new MySqlParameter("AdjNum", adjustment.AdjNum),
					new MySqlParameter("AdjDate", adjustment.AdjDate),
					new MySqlParameter("AdjAmt", adjustment.AdjAmt),
					new MySqlParameter("PatNum", adjustment.PatNum),
					new MySqlParameter("AdjType", adjustment.AdjType),
					new MySqlParameter("ProvNum", adjustment.ProvNum),
					new MySqlParameter("AdjNote", adjustment.AdjNote ?? ""),
					new MySqlParameter("ProcDate", adjustment.ProcDate),
					new MySqlParameter("ProcNum", adjustment.ProcNum),
					new MySqlParameter("DateEntry", adjustment.DateEntry),
					new MySqlParameter("ClinicNum", adjustment.ClinicNum),
					new MySqlParameter("StatementNum", adjustment.StatementNum),
					new MySqlParameter("SecUserNumEntry", adjustment.SecUserNumEntry),
					new MySqlParameter("SecDateTEdit", adjustment.SecDateTEdit));

		/// <summary>
		/// Updates the specified <see cref="Adjustment"/> in the database.
		/// </summary>
		public static void Update(Adjustment adjustmentNew, Adjustment adjustmentOld)
		{
			var updates = new List<string>();
			var parameters = new List<MySqlParameter>();

			if (adjustmentNew.AdjDate != adjustmentOld.AdjDate)
			{
				updates.Add("`AdjDate` = @AdjDate");
				parameters.Add(new MySqlParameter("AdjDate", adjustmentNew.AdjDate));
			}

			if (adjustmentNew.AdjAmt != adjustmentOld.AdjAmt)
			{
				updates.Add("`AdjAmt` = @AdjAmt");
				parameters.Add(new MySqlParameter("AdjAmt", adjustmentNew.AdjAmt));
			}

			if (adjustmentNew.PatNum != adjustmentOld.PatNum)
			{
				updates.Add("`PatNum` = @PatNum");
				parameters.Add(new MySqlParameter("PatNum", adjustmentNew.PatNum));
			}

			if (adjustmentNew.AdjType != adjustmentOld.AdjType)
			{
				updates.Add("`AdjType` = @AdjType");
				parameters.Add(new MySqlParameter("AdjType", adjustmentNew.AdjType));
			}

			if (adjustmentNew.ProvNum != adjustmentOld.ProvNum)
			{
				updates.Add("`ProvNum` = @ProvNum");
				parameters.Add(new MySqlParameter("ProvNum", adjustmentNew.ProvNum));
			}

			if (adjustmentNew.AdjNote != adjustmentOld.AdjNote)
			{
				updates.Add("`AdjNote` = @AdjNote");
				parameters.Add(new MySqlParameter("AdjNote", adjustmentNew.AdjNote ?? ""));
			}

			if (adjustmentNew.ProcDate != adjustmentOld.ProcDate)
			{
				updates.Add("`ProcDate` = @ProcDate");
				parameters.Add(new MySqlParameter("ProcDate", adjustmentNew.ProcDate));
			}

			if (adjustmentNew.ProcNum != adjustmentOld.ProcNum)
			{
				updates.Add("`ProcNum` = @ProcNum");
				parameters.Add(new MySqlParameter("ProcNum", adjustmentNew.ProcNum));
			}

			if (adjustmentNew.DateEntry != adjustmentOld.DateEntry)
			{
				updates.Add("`DateEntry` = @DateEntry");
				parameters.Add(new MySqlParameter("DateEntry", adjustmentNew.DateEntry));
			}

			if (adjustmentNew.ClinicNum != adjustmentOld.ClinicNum)
			{
				updates.Add("`ClinicNum` = @ClinicNum");
				parameters.Add(new MySqlParameter("ClinicNum", adjustmentNew.ClinicNum));
			}

			if (adjustmentNew.StatementNum != adjustmentOld.StatementNum)
			{
				updates.Add("`StatementNum` = @StatementNum");
				parameters.Add(new MySqlParameter("StatementNum", adjustmentNew.StatementNum));
			}

			if (adjustmentNew.SecUserNumEntry != adjustmentOld.SecUserNumEntry)
			{
				updates.Add("`SecUserNumEntry` = @SecUserNumEntry");
				parameters.Add(new MySqlParameter("SecUserNumEntry", adjustmentNew.SecUserNumEntry));
			}

			if (adjustmentNew.SecDateTEdit != adjustmentOld.SecDateTEdit)
			{
				updates.Add("`SecDateTEdit` = @SecDateTEdit");
				parameters.Add(new MySqlParameter("SecDateTEdit", adjustmentNew.SecDateTEdit));
			}

			if (updates.Count == 0) return;

			parameters.Add(new MySqlParameter("AdjNum", adjustmentNew.AdjNum));

			Database.ExecuteNonQuery("UPDATE `Adjustment` " + 
				"SET " + string.Join(", ", updates) + " " + 
				"WHERE `AdjNum` = @AdjNum",
					parameters.ToArray());
		}

		/// <summary>
		/// Deletes a single <see cref="Adjustment"/> object from the database.
		/// </summary>
		public static void Delete(Int64 adjNum)
			 => Database.ExecuteNonQuery("DELETE FROM `Adjustment` WHERE `AdjNum` = " + adjNum);

		/// <summary>
		/// Deletes the specified <see cref="Adjustment"/> object from the database.
		/// </summary>
		public static void Delete(Adjustment adjustment)
			=> Delete(adjustment.AdjNum);
	}
}
