//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using Imedisoft.Data;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;

namespace OpenDentBusiness.Crud{
	public class CanadianNetworkCrud {
		///<summary>Gets one CanadianNetwork object from the database using the primary key.  Returns null if not found.</summary>
		public static CanadianNetwork SelectOne(long canadianNetworkNum) {
			string command="SELECT * FROM canadiannetwork "
				+"WHERE CanadianNetworkNum = "+POut.Long(canadianNetworkNum);
			List<CanadianNetwork> list=TableToList(Database.ExecuteDataTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets one CanadianNetwork object from the database using a query.</summary>
		public static CanadianNetwork SelectOne(string command) {
			List<CanadianNetwork> list=TableToList(Database.ExecuteDataTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets a list of CanadianNetwork objects from the database using a query.</summary>
		public static List<CanadianNetwork> SelectMany(string command) {
			List<CanadianNetwork> list=TableToList(Database.ExecuteDataTable(command));
			return list;
		}

		///<summary>Converts a DataTable to a list of objects.</summary>
		public static List<CanadianNetwork> TableToList(DataTable table) {
			List<CanadianNetwork> retVal=new List<CanadianNetwork>();
			CanadianNetwork canadianNetwork;
			foreach(DataRow row in table.Rows) {
				canadianNetwork=new CanadianNetwork();
				canadianNetwork.Id       = PIn.Long  (row["CanadianNetworkNum"].ToString());
				canadianNetwork.Abbr                   = PIn.String(row["Abbrev"].ToString());
				canadianNetwork.Description                 = PIn.String(row["Descript"].ToString());
				canadianNetwork.TransactionPrefix= PIn.String(row["CanadianTransactionPrefix"].ToString());
				canadianNetwork.IsRprHandler     = PIn.Bool  (row["CanadianIsRprHandler"].ToString());
				retVal.Add(canadianNetwork);
			}
			return retVal;
		}

		///<summary>Converts a list of CanadianNetwork into a DataTable.</summary>
		public static DataTable ListToTable(List<CanadianNetwork> listCanadianNetworks,string tableName="") {
			if(string.IsNullOrEmpty(tableName)) {
				tableName="CanadianNetwork";
			}
			DataTable table=new DataTable(tableName);
			table.Columns.Add("CanadianNetworkNum");
			table.Columns.Add("Abbrev");
			table.Columns.Add("Descript");
			table.Columns.Add("CanadianTransactionPrefix");
			table.Columns.Add("CanadianIsRprHandler");
			foreach(CanadianNetwork canadianNetwork in listCanadianNetworks) {
				table.Rows.Add(new object[] {
					POut.Long  (canadianNetwork.Id),
					            canadianNetwork.Abbr,
					            canadianNetwork.Description,
					            canadianNetwork.TransactionPrefix,
					POut.Bool  (canadianNetwork.IsRprHandler),
				});
			}
			return table;
		}

		///<summary>Inserts one CanadianNetwork into the database.  Returns the new priKey.</summary>
		public static long Insert(CanadianNetwork canadianNetwork) {
			return Insert(canadianNetwork,false);
		}

		///<summary>Inserts one CanadianNetwork into the database.  Provides option to use the existing priKey.</summary>
		public static long Insert(CanadianNetwork canadianNetwork,bool useExistingPK) {
			if(!useExistingPK && PrefC.RandomKeys) {
				canadianNetwork.Id=ReplicationServers.GetKey("canadiannetwork","CanadianNetworkNum");
			}
			string command="INSERT INTO canadiannetwork (";
			if(useExistingPK || PrefC.RandomKeys) {
				command+="CanadianNetworkNum,";
			}
			command+="Abbrev,Descript,CanadianTransactionPrefix,CanadianIsRprHandler) VALUES(";
			if(useExistingPK || PrefC.RandomKeys) {
				command+=POut.Long(canadianNetwork.Id)+",";
			}
			command+=
				 "'"+POut.String(canadianNetwork.Abbr)+"',"
				+"'"+POut.String(canadianNetwork.Description)+"',"
				+"'"+POut.String(canadianNetwork.TransactionPrefix)+"',"
				+    POut.Bool  (canadianNetwork.IsRprHandler)+")";
			if(useExistingPK || PrefC.RandomKeys) {
				Database.ExecuteNonQuery(command);
			}
			else {
				canadianNetwork.Id=Database.ExecuteInsert(command);
			}
			return canadianNetwork.Id;
		}

		///<summary>Inserts one CanadianNetwork into the database.  Returns the new priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(CanadianNetwork canadianNetwork) {
			return InsertNoCache(canadianNetwork,false);
		}

		///<summary>Inserts one CanadianNetwork into the database.  Provides option to use the existing priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(CanadianNetwork canadianNetwork,bool useExistingPK) {
			
			string command="INSERT INTO canadiannetwork (";
			if(!useExistingPK) {
				canadianNetwork.Id=ReplicationServers.GetKeyNoCache("canadiannetwork","CanadianNetworkNum");
			}
			if(useExistingPK) {
				command+="CanadianNetworkNum,";
			}
			command+="Abbrev,Descript,CanadianTransactionPrefix,CanadianIsRprHandler) VALUES(";
			if(useExistingPK) {
				command+=POut.Long(canadianNetwork.Id)+",";
			}
			command+=
				 "'"+POut.String(canadianNetwork.Abbr)+"',"
				+"'"+POut.String(canadianNetwork.Description)+"',"
				+"'"+POut.String(canadianNetwork.TransactionPrefix)+"',"
				+    POut.Bool  (canadianNetwork.IsRprHandler)+")";
			if(useExistingPK) {
				Database.ExecuteNonQuery(command);
			}
			else {
				canadianNetwork.Id=Database.ExecuteInsert(command);
			}
			return canadianNetwork.Id;
		}

		///<summary>Updates one CanadianNetwork in the database.</summary>
		public static void Update(CanadianNetwork canadianNetwork) {
			string command="UPDATE canadiannetwork SET "
				+"Abbrev                   = '"+POut.String(canadianNetwork.Abbr)+"', "
				+"Descript                 = '"+POut.String(canadianNetwork.Description)+"', "
				+"CanadianTransactionPrefix= '"+POut.String(canadianNetwork.TransactionPrefix)+"', "
				+"CanadianIsRprHandler     =  "+POut.Bool  (canadianNetwork.IsRprHandler)+" "
				+"WHERE CanadianNetworkNum = "+POut.Long(canadianNetwork.Id);
			Database.ExecuteNonQuery(command);
		}

		///<summary>Updates one CanadianNetwork in the database.  Uses an old object to compare to, and only alters changed fields.  This prevents collisions and concurrency problems in heavily used tables.  Returns true if an update occurred.</summary>
		public static bool Update(CanadianNetwork canadianNetwork,CanadianNetwork oldCanadianNetwork) {
			string command="";
			if(canadianNetwork.Abbr != oldCanadianNetwork.Abbr) {
				if(command!="") { command+=",";}
				command+="Abbrev = '"+POut.String(canadianNetwork.Abbr)+"'";
			}
			if(canadianNetwork.Description != oldCanadianNetwork.Description) {
				if(command!="") { command+=",";}
				command+="Descript = '"+POut.String(canadianNetwork.Description)+"'";
			}
			if(canadianNetwork.TransactionPrefix != oldCanadianNetwork.TransactionPrefix) {
				if(command!="") { command+=",";}
				command+="CanadianTransactionPrefix = '"+POut.String(canadianNetwork.TransactionPrefix)+"'";
			}
			if(canadianNetwork.IsRprHandler != oldCanadianNetwork.IsRprHandler) {
				if(command!="") { command+=",";}
				command+="CanadianIsRprHandler = "+POut.Bool(canadianNetwork.IsRprHandler)+"";
			}
			if(command=="") {
				return false;
			}
			command="UPDATE canadiannetwork SET "+command
				+" WHERE CanadianNetworkNum = "+POut.Long(canadianNetwork.Id);
			Database.ExecuteNonQuery(command);
			return true;
		}

		///<summary>Returns true if Update(CanadianNetwork,CanadianNetwork) would make changes to the database.
		///Does not make any changes to the database and can be called before remoting role is checked.</summary>
		public static bool UpdateComparison(CanadianNetwork canadianNetwork,CanadianNetwork oldCanadianNetwork) {
			if(canadianNetwork.Abbr != oldCanadianNetwork.Abbr) {
				return true;
			}
			if(canadianNetwork.Description != oldCanadianNetwork.Description) {
				return true;
			}
			if(canadianNetwork.TransactionPrefix != oldCanadianNetwork.TransactionPrefix) {
				return true;
			}
			if(canadianNetwork.IsRprHandler != oldCanadianNetwork.IsRprHandler) {
				return true;
			}
			return false;
		}

		///<summary>Deletes one CanadianNetwork from the database.</summary>
		public static void Delete(long canadianNetworkNum) {
			string command="DELETE FROM canadiannetwork "
				+"WHERE CanadianNetworkNum = "+POut.Long(canadianNetworkNum);
			Database.ExecuteNonQuery(command);
		}

	}
}