//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using Imedisoft.Data;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;

namespace OpenDentBusiness.Crud{
	public class CountyCrud {
		///<summary>Gets one County object from the database using the primary key.  Returns null if not found.</summary>
		public static County SelectOne(long countyNum) {
			string command="SELECT * FROM county "
				+"WHERE CountyNum = "+POut.Long(countyNum);
			List<County> list=TableToList(Database.ExecuteDataTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets one County object from the database using a query.</summary>
		public static County SelectOne(string command) {

			List<County> list=TableToList(Database.ExecuteDataTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets a list of County objects from the database using a query.</summary>
		public static List<County> SelectMany(string command) {

			List<County> list=TableToList(Database.ExecuteDataTable(command));
			return list;
		}

		///<summary>Converts a DataTable to a list of objects.</summary>
		public static List<County> TableToList(DataTable table) {
			List<County> retVal=new List<County>();
			County county;
			foreach(DataRow row in table.Rows) {
				county=new County();
				county.Id = PIn.Long  (row["CountyNum"].ToString());
				county.Name= PIn.String(row["CountyName"].ToString());
				county.Code= PIn.String(row["CountyCode"].ToString());
				retVal.Add(county);
			}
			return retVal;
		}

		///<summary>Converts a list of County into a DataTable.</summary>
		public static DataTable ListToTable(List<County> listCountys,string tableName="") {
			if(string.IsNullOrEmpty(tableName)) {
				tableName="County";
			}
			DataTable table=new DataTable(tableName);
			table.Columns.Add("CountyNum");
			table.Columns.Add("CountyName");
			table.Columns.Add("CountyCode");
			foreach(County county in listCountys) {
				table.Rows.Add(new object[] {
					POut.Long  (county.Id),
					            county.Name,
					            county.Code,
				});
			}
			return table;
		}

		///<summary>Inserts one County into the database.  Returns the new priKey.</summary>
		public static long Insert(County county) {
			return Insert(county,false);
		}

		///<summary>Inserts one County into the database.  Provides option to use the existing priKey.</summary>
		public static long Insert(County county,bool useExistingPK) {
			if(!useExistingPK && PrefC.RandomKeys) {
				county.Id=ReplicationServers.GetKey("county","CountyNum");
			}
			string command="INSERT INTO county (";
			if(useExistingPK || PrefC.RandomKeys) {
				command+="CountyNum,";
			}
			command+="CountyName,CountyCode) VALUES(";
			if(useExistingPK || PrefC.RandomKeys) {
				command+=POut.Long(county.Id)+",";
			}
			command+=
				 "'"+POut.String(county.Name)+"',"
				+"'"+POut.String(county.Code)+"')";
			if(useExistingPK || PrefC.RandomKeys) {
				Database.ExecuteNonQuery(command);
			}
			else {
				county.Id=Database.ExecuteInsert(command);
			}
			return county.Id;
		}

		///<summary>Inserts one County into the database.  Returns the new priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(County county) {
			return InsertNoCache(county,false);
		}

		///<summary>Inserts one County into the database.  Provides option to use the existing priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(County county,bool useExistingPK) {
			
			string command="INSERT INTO county (";
			if(!useExistingPK) {
				county.Id=ReplicationServers.GetKeyNoCache("county","CountyNum");
			}
			if(useExistingPK) {
				command+="CountyNum,";
			}
			command+="CountyName,CountyCode) VALUES(";
			if(useExistingPK) {
				command+=POut.Long(county.Id)+",";
			}
			command+=
				 "'"+POut.String(county.Name)+"',"
				+"'"+POut.String(county.Code)+"')";
			if(useExistingPK) {
				Database.ExecuteNonQuery(command);
			}
			else {
				county.Id=Database.ExecuteInsert(command);
			}
			return county.Id;
		}

		///<summary>Updates one County in the database.</summary>
		public static void Update(County county) {
			string command="UPDATE county SET "
				+"CountyName= '"+POut.String(county.Name)+"', "
				+"CountyCode= '"+POut.String(county.Code)+"' "
				+"WHERE CountyNum = "+POut.Long(county.Id);
			Database.ExecuteNonQuery(command);
		}

		///<summary>Updates one County in the database.  Uses an old object to compare to, and only alters changed fields.  This prevents collisions and concurrency problems in heavily used tables.  Returns true if an update occurred.</summary>
		public static bool Update(County county,County oldCounty) {
			string command="";
			if(county.Name != oldCounty.Name) {
				if(command!="") { command+=",";}
				command+="CountyName = '"+POut.String(county.Name)+"'";
			}
			if(county.Code != oldCounty.Code) {
				if(command!="") { command+=",";}
				command+="CountyCode = '"+POut.String(county.Code)+"'";
			}
			if(command=="") {
				return false;
			}
			command="UPDATE county SET "+command
				+" WHERE CountyNum = "+POut.Long(county.Id);
			Database.ExecuteNonQuery(command);
			return true;
		}

		///<summary>Returns true if Update(County,County) would make changes to the database.
		///Does not make any changes to the database and can be called before remoting role is checked.</summary>
		public static bool UpdateComparison(County county,County oldCounty) {
			if(county.Name != oldCounty.Name) {
				return true;
			}
			if(county.Code != oldCounty.Code) {
				return true;
			}
			return false;
		}

		///<summary>Deletes one County from the database.</summary>
		public static void Delete(long countyNum) {
			string command="DELETE FROM county "
				+"WHERE CountyNum = "+POut.Long(countyNum);
			Database.ExecuteNonQuery(command);
		}

	}
}