//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using Imedisoft.Data;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;

namespace OpenDentBusiness.Crud
{
    public class EmployerCrud
	{
		///<summary>Gets one Employer object from the database using the primary key.  Returns null if not found.</summary>
		public static Employer SelectOne(long employerNum)
		{
			string command = "SELECT * FROM employer "
				+ "WHERE EmployerNum = " + POut.Long(employerNum);
			List<Employer> list = TableToList(Database.ExecuteDataTable(command));
			if (list.Count == 0)
			{
				return null;
			}
			return list[0];
		}

		///<summary>Gets one Employer object from the database using a query.</summary>
		public static Employer SelectOne(string command)
		{

			List<Employer> list = TableToList(Database.ExecuteDataTable(command));
			if (list.Count == 0)
			{
				return null;
			}
			return list[0];
		}

		///<summary>Gets a list of Employer objects from the database using a query.</summary>
		public static List<Employer> SelectMany(string command)
		{

			List<Employer> list = TableToList(Database.ExecuteDataTable(command));
			return list;
		}

		///<summary>Converts a DataTable to a list of objects.</summary>
		public static List<Employer> TableToList(DataTable table)
		{
			List<Employer> retVal = new List<Employer>();
			Employer employer;
			foreach (DataRow row in table.Rows)
			{
				employer = new Employer();
				employer.Id = PIn.Long(row["EmployerNum"].ToString());
				employer.Name = PIn.String(row["EmpName"].ToString());
				employer.Phone = PIn.String(row["Phone"].ToString());
				retVal.Add(employer);
			}
			return retVal;
		}

		///<summary>Converts a list of Employer into a DataTable.</summary>
		public static DataTable ListToTable(List<Employer> listEmployers, string tableName = "")
		{
			if (string.IsNullOrEmpty(tableName))
			{
				tableName = "Employer";
			}
			DataTable table = new DataTable(tableName);
			table.Columns.Add("EmployerNum");
			table.Columns.Add("EmpName");
			table.Columns.Add("Phone");
			foreach (Employer employer in listEmployers)
			{
				table.Rows.Add(new object[] {
					POut.Long  (employer.Id),
								employer.Name,
								employer.Phone,
				});
			}
			return table;
		}

		///<summary>Inserts one Employer into the database.  Returns the new priKey.</summary>
		public static long Insert(Employer employer)
		{
			return Insert(employer, false);
		}

		///<summary>Inserts one Employer into the database.  Provides option to use the existing priKey.</summary>
		public static long Insert(Employer employer, bool useExistingPK)
		{
			if (!useExistingPK && PrefC.RandomKeys)
			{
				employer.Id = ReplicationServers.GetKey("employer", "EmployerNum");
			}
			string command = "INSERT INTO employer (";
			if (useExistingPK || PrefC.RandomKeys)
			{
				command += "EmployerNum,";
			}
			command += "EmpName,Phone) VALUES(";
			if (useExistingPK || PrefC.RandomKeys)
			{
				command += POut.Long(employer.Id) + ",";
			}
			command +=
				 "'" + POut.String(employer.Name) + "',"
				+ "'" + POut.String(employer.Phone) + "')";
			if (useExistingPK || PrefC.RandomKeys)
			{
				Database.ExecuteNonQuery(command);
			}
			else
			{
				employer.Id = Database.ExecuteInsert(command);
			}
			return employer.Id;
		}

		///<summary>Inserts one Employer into the database.  Returns the new priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(Employer employer)
		{
			return InsertNoCache(employer, false);
		}

		///<summary>Inserts one Employer into the database.  Provides option to use the existing priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(Employer employer, bool useExistingPK)
		{

			string command = "INSERT INTO employer (";
			if (!useExistingPK)
			{
				employer.Id = ReplicationServers.GetKeyNoCache("employer", "EmployerNum");
			}
			if (useExistingPK)
			{
				command += "EmployerNum,";
			}
			command += "EmpName,Phone) VALUES(";
			if (useExistingPK)
			{
				command += POut.Long(employer.Id) + ",";
			}
			command +=
				 "'" + POut.String(employer.Name) + "',"
				+ "'" + POut.String(employer.Phone) + "')";
			if (useExistingPK)
			{
				Database.ExecuteNonQuery(command);
			}
			else
			{
				employer.Id = Database.ExecuteInsert(command);
			}
			return employer.Id;
		}

		///<summary>Updates one Employer in the database.</summary>
		public static void Update(Employer employer)
		{
			string command = "UPDATE employer SET "
				+ "EmpName    = '" + POut.String(employer.Name) + "', "
				+ "Phone      = '" + POut.String(employer.Phone) + "' "
				+ "WHERE EmployerNum = " + POut.Long(employer.Id);
			Database.ExecuteNonQuery(command);
		}

		///<summary>Updates one Employer in the database.  Uses an old object to compare to, and only alters changed fields.  This prevents collisions and concurrency problems in heavily used tables.  Returns true if an update occurred.</summary>
		public static bool Update(Employer employer, Employer oldEmployer)
		{
			string command = "";
			if (employer.Name != oldEmployer.Name)
			{
				if (command != "") { command += ","; }
				command += "EmpName = '" + POut.String(employer.Name) + "'";
			}
			if (employer.Phone != oldEmployer.Phone)
			{
				if (command != "") { command += ","; }
				command += "Phone = '" + POut.String(employer.Phone) + "'";
			}
			if (command == "")
			{
				return false;
			}
			command = "UPDATE employer SET " + command
				+ " WHERE EmployerNum = " + POut.Long(employer.Id);
			Database.ExecuteNonQuery(command);
			return true;
		}

		///<summary>Returns true if Update(Employer,Employer) would make changes to the database.
		///Does not make any changes to the database and can be called before remoting role is checked.</summary>
		public static bool UpdateComparison(Employer employer, Employer oldEmployer)
		{
			if (employer.Name != oldEmployer.Name)
			{
				return true;
			}
			if (employer.Phone != oldEmployer.Phone)
			{
				return true;
			}
			return false;
		}

		///<summary>Deletes one Employer from the database.</summary>
		public static void Delete(long employerNum)
		{
			string command = "DELETE FROM employer "
				+ "WHERE EmployerNum = " + POut.Long(employerNum);
			Database.ExecuteNonQuery(command);
		}
	}
}
