//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using Imedisoft.Data;
using MySql.Data.MySqlClient;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;

namespace OpenDentBusiness.Crud{
	public class PrefCrud {
		///<summary>Gets one Pref object from the database using the primary key.  Returns null if not found.</summary>
		public static Pref SelectOne(long prefNum) {
			string command="SELECT * FROM preference "
				+"WHERE PrefNum = "+POut.Long(prefNum);
			List<Pref> list=TableToList(Database.ExecuteDataTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets one Pref object from the database using a query.</summary>
		public static Pref SelectOne(string command) {

			List<Pref> list=TableToList(Database.ExecuteDataTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets a list of Pref objects from the database using a query.</summary>
		public static List<Pref> SelectMany(string command) {

			List<Pref> list=TableToList(Database.ExecuteDataTable(command));
			return list;
		}

		///<summary>Converts a DataTable to a list of objects.</summary>
		public static List<Pref> TableToList(DataTable table) {
			List<Pref> retVal=new List<Pref>();
			Pref pref;
			foreach(DataRow row in table.Rows) {
				pref=new Pref();
				pref.Id    = PIn.Long  (row["PrefNum"].ToString());
				pref.Name   = PIn.String(row["PrefName"].ToString());
				pref.Value= PIn.String(row["ValueString"].ToString());
				pref.Comments   = PIn.String(row["Comments"].ToString());
				retVal.Add(pref);
			}
			return retVal;
		}

		///<summary>Converts a list of Pref into a DataTable.</summary>
		public static DataTable ListToTable(List<Pref> listPrefs,string tableName="") {
			if(string.IsNullOrEmpty(tableName)) {
				tableName="Pref";
			}
			DataTable table=new DataTable(tableName);
			table.Columns.Add("PrefNum");
			table.Columns.Add("PrefName");
			table.Columns.Add("ValueString");
			table.Columns.Add("Comments");
			foreach(Pref pref in listPrefs) {
				table.Rows.Add(new object[] {
					POut.Long  (pref.Id),
					            pref.Name,
					            pref.Value,
					            pref.Comments,
				});
			}
			return table;
		}

		///<summary>Inserts one Pref into the database.  Returns the new priKey.</summary>
		public static long Insert(Pref pref) {
			return Insert(pref,false);
		}

		///<summary>Inserts one Pref into the database.  Provides option to use the existing priKey.</summary>
		public static long Insert(Pref pref,bool useExistingPK) {
			if(!useExistingPK && PrefC.RandomKeys) {
				pref.Id=ReplicationServers.GetKey("preference","PrefNum");
			}
			string command="INSERT INTO preference (";
			if(useExistingPK || PrefC.RandomKeys) {
				command+="PrefNum,";
			}
			command+="PrefName,ValueString,Comments) VALUES(";
			if(useExistingPK || PrefC.RandomKeys) {
				command+=POut.Long(pref.Id)+",";
			}
			command+=
				 "'"+POut.String(pref.Name)+"',"
				+    DbHelper.ParamChar+"paramValueString,"
				+    DbHelper.ParamChar+"paramComments)";
			if(pref.Value==null) {
				pref.Value="";
			}
			var paramValueString = new MySqlParameter("paramValueString", POut.StringParam(pref.Value));
			if(pref.Comments==null) {
				pref.Comments="";
			}
			var paramComments = new MySqlParameter("paramComments", POut.StringParam(pref.Comments));
			if(useExistingPK || PrefC.RandomKeys) {
				Database.ExecuteNonQuery(command,paramValueString,paramComments);
			}
			else {
				pref.Id=Database.ExecuteInsert(command,paramValueString,paramComments);
			}
			return pref.Id;
		}

		///<summary>Inserts one Pref into the database.  Returns the new priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(Pref pref) {
			return InsertNoCache(pref,false);
		}

		///<summary>Inserts one Pref into the database.  Provides option to use the existing priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(Pref pref,bool useExistingPK) {
			
			string command="INSERT INTO preference (";
			if(!useExistingPK) {
				pref.Id=ReplicationServers.GetKeyNoCache("preference","PrefNum");
			}
			if(useExistingPK) {
				command+="PrefNum,";
			}
			command+="PrefName,ValueString,Comments) VALUES(";
			if(useExistingPK) {
				command+=POut.Long(pref.Id)+",";
			}
			command+=
				 "'"+POut.String(pref.Name)+"',"
				+    DbHelper.ParamChar+"paramValueString,"
				+    DbHelper.ParamChar+"paramComments)";
			if(pref.Value==null) {
				pref.Value="";
			}
			var paramValueString = new MySqlParameter("paramValueString", POut.StringParam(pref.Value));
			if(pref.Comments==null) {
				pref.Comments="";
			}
			var paramComments = new MySqlParameter("paramComments", POut.StringParam(pref.Comments));
			if(useExistingPK) {
				Database.ExecuteNonQuery(command,paramValueString,paramComments);
			}
			else {
				pref.Id=Database.ExecuteInsert(command,paramValueString,paramComments);
			}
			return pref.Id;
		}

		///<summary>Updates one Pref in the database.</summary>
		public static void Update(Pref pref) {
			string command="UPDATE preference SET "
				+"PrefName   = '"+POut.String(pref.Name)+"', "
				+"ValueString=  "+DbHelper.ParamChar+"paramValueString, "
				+"Comments   =  "+DbHelper.ParamChar+"paramComments "
				+"WHERE PrefNum = "+POut.Long(pref.Id);
			if(pref.Value==null) {
				pref.Value="";
			}
			var paramValueString = new MySqlParameter("paramValueString", POut.StringParam(pref.Value));
			if(pref.Comments==null) {
				pref.Comments="";
			}
			var paramComments = new MySqlParameter("paramComments", POut.StringParam(pref.Comments));
			Database.ExecuteNonQuery(command,paramValueString,paramComments);
		}

		///<summary>Updates one Pref in the database.  Uses an old object to compare to, and only alters changed fields.  This prevents collisions and concurrency problems in heavily used tables.  Returns true if an update occurred.</summary>
		public static bool Update(Pref pref,Pref oldPref) {
			string command="";
			if(pref.Name != oldPref.Name) {
				if(command!="") { command+=",";}
				command+="PrefName = '"+POut.String(pref.Name)+"'";
			}
			if(pref.Value != oldPref.Value) {
				if(command!="") { command+=",";}
				command+="ValueString = "+DbHelper.ParamChar+"paramValueString";
			}
			if(pref.Comments != oldPref.Comments) {
				if(command!="") { command+=",";}
				command+="Comments = "+DbHelper.ParamChar+"paramComments";
			}
			if(command=="") {
				return false;
			}
			if(pref.Value==null) {
				pref.Value="";
			}
			var paramValueString = new MySqlParameter("paramValueString", POut.StringParam(pref.Value));
			if(pref.Comments==null) {
				pref.Comments="";
			}
			var paramComments = new MySqlParameter("paramComments", POut.StringParam(pref.Comments));
			command="UPDATE preference SET "+command
				+" WHERE PrefNum = "+POut.Long(pref.Id);
			Database.ExecuteNonQuery(command,paramValueString,paramComments);
			return true;
		}

		///<summary>Returns true if Update(Pref,Pref) would make changes to the database.
		///Does not make any changes to the database and can be called before remoting role is checked.</summary>
		public static bool UpdateComparison(Pref pref,Pref oldPref) {
			if(pref.Name != oldPref.Name) {
				return true;
			}
			if(pref.Value != oldPref.Value) {
				return true;
			}
			if(pref.Comments != oldPref.Comments) {
				return true;
			}
			return false;
		}

		///<summary>Deletes one Pref from the database.</summary>
		public static void Delete(long prefNum) {
			string command="DELETE FROM preference "
				+"WHERE PrefNum = "+POut.Long(prefNum);
			Database.ExecuteNonQuery(command);
		}

	}
}