//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Imedisoft.Data.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;

namespace Imedisoft.Data
{
	public partial class EhrCarePlans
	{
		public static EhrCarePlan FromReader(MySqlDataReader dataReader)
		{
			return new EhrCarePlan
			{
				Id = (long)dataReader["id"],
				PatientId = (long)dataReader["patient_id"],
				SnomedEducation = (string)dataReader["snomed_education"],
				Instructions = (string)dataReader["instructions"],
				DatePlanned = dataReader["date_planned"] as DateTime?
			};
		}

		/// <summary>
		/// Selects a single EhrCarePlan object from the database using the specified SQL command.
		/// </summary>
		/// <param name="command">The SELECT command to execute.</param>
		/// <param name="parameters">The (optional) command parameters.</param>
		public static EhrCarePlan SelectOne(string command, params MySqlParameter[] parameters)
			=> Database.SelectOne(command, FromReader, parameters);

		/// <summary>
		/// Selects the <see cref="EhrCarePlan"/> object with the specified key from the database.
		/// </summary>
		/// <param name="id">The primary key of the <see cref="EhrCarePlan"/> to select.</param>
		public static EhrCarePlan SelectOne(long id)
			=> SelectOne("SELECT * FROM `ehr_care_plans` WHERE `id` = " + id);

		/// <summary>
		/// Selects multiple <see cref="EhrCarePlan"/> objects from the database using the specified SQL command.
		/// </summary>
		/// <param name="command">The SELECT command to execute.</param>
		/// <param name="parameters">The (optional) command parameters.</param>
		public static IEnumerable<EhrCarePlan> SelectMany(string command, params MySqlParameter[] parameters)
			=> Database.SelectMany(command, FromReader, parameters);

		/// <summary>
		/// Inserts the specified <see cref="EhrCarePlan"/> into the database.
		/// </summary>
		/// <param name="ehrCarePlan">The <see cref="EhrCarePlan"/> to insert into the database.</param>
		private static long ExecuteInsert(EhrCarePlan ehrCarePlan)
			=> ehrCarePlan.Id = Database.ExecuteInsert(
				"INSERT INTO `ehr_care_plans` " +
				"(`patient_id`, `snomed_education`, `instructions`, `date_planned`) " +
				"VALUES (" +
					"@patient_id, @snomed_education, @instructions, @date_planned" +
				")",
					new MySqlParameter("patient_id", ehrCarePlan.PatientId),
					new MySqlParameter("snomed_education", ehrCarePlan.SnomedEducation ?? ""),
					new MySqlParameter("instructions", ehrCarePlan.Instructions ?? ""),
					new MySqlParameter("date_planned", (ehrCarePlan.DatePlanned.HasValue ? (object)ehrCarePlan.DatePlanned.Value : DBNull.Value)));

		/// <summary>
		/// Updates the specified <see cref="EhrCarePlan"/> in the database.
		/// </summary>
		/// <param name="ehrCarePlan">The <see cref="EhrCarePlan"/> to update.</param>
		private static void ExecuteUpdate(EhrCarePlan ehrCarePlan)
			=> Database.ExecuteNonQuery(
				"UPDATE `ehr_care_plans` SET " +
					"`patient_id` = @patient_id, " +
					"`snomed_education` = @snomed_education, " +
					"`instructions` = @instructions, " +
					"`date_planned` = @date_planned " +
				"WHERE `id` = @id",
					new MySqlParameter("id", ehrCarePlan.Id),
					new MySqlParameter("patient_id", ehrCarePlan.PatientId),
					new MySqlParameter("snomed_education", ehrCarePlan.SnomedEducation ?? ""),
					new MySqlParameter("instructions", ehrCarePlan.Instructions ?? ""),
					new MySqlParameter("date_planned", (ehrCarePlan.DatePlanned.HasValue ? (object)ehrCarePlan.DatePlanned.Value : DBNull.Value)));

		/// <summary>
		/// Deletes a single <see cref="EhrCarePlan"/> object from the database.
		/// </summary>
		/// <param name="id">The primary key of the <see cref="EhrCarePlan"/> to delete.</param>
		private static void ExecuteDelete(long id)
			 => Database.ExecuteNonQuery("DELETE FROM `ehr_care_plans` WHERE `id` = " + id);

		/// <summary>
		/// Deletes the specified <see cref="EhrCarePlan"/> object from the database.
		/// </summary>
		/// <param name="ehrCarePlan">The <see cref="EhrCarePlan"/> to delete.</param>
		private static void ExecuteDelete(EhrCarePlan ehrCarePlan)
			=> ExecuteDelete(ehrCarePlan.Id);
	}
}
