//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Imedisoft.Data.Models;
using MySql.Data.MySqlClient;
using System.Collections.Generic;

namespace Imedisoft.Data
{
    public partial class EhrVaccines
	{
		public static EhrVaccine FromReader(MySqlDataReader dataReader)
		{
			return new EhrVaccine
			{
				Id = (long)dataReader["id"],
				EhrDrugManufacturerId = (long)dataReader["ehr_drug_manufacturer_id"],
				CvxCode = (string)dataReader["cvx_code"],
				Name = (string)dataReader["name"]
			};
		}

		/// <summary>
		/// Selects a single EhrVaccine object from the database using the specified SQL command.
		/// </summary>
		/// <param name="command">The SELECT command to execute.</param>
		/// <param name="parameters">The (optional) command parameters.</param>
		public static EhrVaccine SelectOne(string command, params MySqlParameter[] parameters)
			=> Database.SelectOne(command, FromReader, parameters);

		/// <summary>
		/// Selects the <see cref="EhrVaccine"/> object with the specified key from the database.
		/// </summary>
		/// <param name="id">The primary key of the <see cref="EhrVaccine"/> to select.</param>
		public static EhrVaccine SelectOne(long id)
			=> SelectOne("SELECT * FROM `ehr_vaccines` WHERE `id` = " + id);

		/// <summary>
		/// Selects multiple <see cref="EhrVaccine"/> objects from the database using the specified SQL command.
		/// </summary>
		/// <param name="command">The SELECT command to execute.</param>
		/// <param name="parameters">The (optional) command parameters.</param>
		public static IEnumerable<EhrVaccine> SelectMany(string command, params MySqlParameter[] parameters)
			=> Database.SelectMany(command, FromReader, parameters);

		/// <summary>
		/// Inserts the specified <see cref="EhrVaccine"/> into the database.
		/// </summary>
		/// <param name="ehrVaccine">The <see cref="EhrVaccine"/> to insert into the database.</param>
		private static long ExecuteInsert(EhrVaccine ehrVaccine)
			=> ehrVaccine.Id = Database.ExecuteInsert(
				"INSERT INTO `ehr_vaccines` " +
				"(`ehr_drug_manufacturer_id`, `cvx_code`, `name`) " +
				"VALUES (" +
					"@ehr_drug_manufacturer_id, @cvx_code, @name" +
				")",
					new MySqlParameter("ehr_drug_manufacturer_id", ehrVaccine.EhrDrugManufacturerId),
					new MySqlParameter("cvx_code", ehrVaccine.CvxCode ?? ""),
					new MySqlParameter("name", ehrVaccine.Name ?? ""));

		/// <summary>
		/// Updates the specified <see cref="EhrVaccine"/> in the database.
		/// </summary>
		/// <param name="ehrVaccine">The <see cref="EhrVaccine"/> to update.</param>
		private static void ExecuteUpdate(EhrVaccine ehrVaccine)
			=> Database.ExecuteNonQuery(
				"UPDATE `ehr_vaccines` SET " +
					"`ehr_drug_manufacturer_id` = @ehr_drug_manufacturer_id, " +
					"`cvx_code` = @cvx_code, " +
					"`name` = @name " +
				"WHERE `id` = @id",
					new MySqlParameter("id", ehrVaccine.Id),
					new MySqlParameter("ehr_drug_manufacturer_id", ehrVaccine.EhrDrugManufacturerId),
					new MySqlParameter("cvx_code", ehrVaccine.CvxCode ?? ""),
					new MySqlParameter("name", ehrVaccine.Name ?? ""));

		/// <summary>
		/// Deletes a single <see cref="EhrVaccine"/> object from the database.
		/// </summary>
		/// <param name="id">The primary key of the <see cref="EhrVaccine"/> to delete.</param>
		private static void ExecuteDelete(long id)
			 => Database.ExecuteNonQuery("DELETE FROM `ehr_vaccines` WHERE `id` = " + id);

		/// <summary>
		/// Deletes the specified <see cref="EhrVaccine"/> object from the database.
		/// </summary>
		/// <param name="ehrVaccine">The <see cref="EhrVaccine"/> to delete.</param>
		private static void ExecuteDelete(EhrVaccine ehrVaccine)
			=> ExecuteDelete(ehrVaccine.Id);
	}
}
